# simplified haskell-ci Travis setup
# see also https://github.com/haskell-CI/haskell-ci

language: haskell

cache:
  directories:
   - $HOME/.cabal/store

cabal: 2.4
ghc:
  - "8.6.3"
  - "8.4.4"
  - "8.2.2"
  - "8.0.2"
  - "7.10.3"

install:
 - cabal --version
 - ghc --version

script:
 - cabal v2-update
 - cabal v2-build exes
 - cabal check
 - cabal v2-run exe:summer-of-haskell -- check --internal-links
